max_epochs: 100000
dqn_type: RainbowDQN
network_type: mlp_noisy  # Noisy DQN
replay_buffer_type: prioritized  # Prioritized DQN
env: MinAtar/Freeway
device: cpu
rollouts_per_validation: 3
validate_every_n_epochs: 1000